version: '3.3'
services:
  db:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=subway
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}